# Generated by Django 2.0.7 on 2018-07-04 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome:')),
                ('idade', models.IntegerField(verbose_name='Idade:')),
                ('datade_nascimento', models.DateField(verbose_name='Data de Nascimento:')),
                ('rg', models.IntegerField(unique=True, verbose_name='RG:')),
                ('ssp', models.CharField(max_length=4, verbose_name='SS/P:')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF:')),
                ('cartao_sus', models.CharField(max_length=20, verbose_name='Cartão do SUS:')),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=1, verbose_name='Sexo:')),
                ('raca', models.CharField(choices=[('B', 'Branca'), ('N', 'Negra'), ('P', 'Parda')], max_length=1, verbose_name='Raça:')),
                ('proficao', models.CharField(max_length=100, verbose_name='Profissão/escolaridade:')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço:')),
                ('numero', models.IntegerField(verbose_name='Numero:')),
                ('bairro', models.CharField(max_length=150, verbose_name='Bairro:')),
                ('fonefixo', models.CharField(max_length=10, verbose_name='Telefone Fixo:')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular:')),
                ('procedencia', models.CharField(max_length=155, verbose_name='Procedencia:')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['date_created'],
            },
        ),
        migrations.AlterModelOptions(
            name='agentedesaude',
            options={'ordering': ['nome'], 'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes'},
        ),
        migrations.AddField(
            model_name='cadastropaciente',
            name='agente_saude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medsis.AgenteDeSaude', verbose_name='Agente de Saude:'),
        ),
    ]
