# Generated by Django 2.0.7 on 2018-07-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsis', '0002_auto_20180703_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentedesaude',
            name='rg',
            field=models.CharField(max_length=15, unique=True, verbose_name='RG:'),
        ),
    ]
