# Generated by Django 2.0.2 on 2018-07-11 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medsis', '0003_auto_20180706_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentedesaude',
            options={'ordering': ['nome'], 'permissions': (('pode_mudar_status', 'Pode mudar status'), ('pode_fazer_outra_coisa', 'Pode fazer outra coisa')), 'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes'},
        ),
    ]
