# Generated by Django 2.0.2 on 2018-07-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medsis', '0004_auto_20180710_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentedesaude',
            options={'ordering': ['nome'], 'permissions': (('add_agente', 'Pode Adicionar Agente'), ('delet_agente', 'Pode fazer outra coisa')), 'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes'},
        ),
    ]
