# Generated by Django 2.0.2 on 2018-07-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medsis', '0007_auto_20180730_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentedesaude',
            options={'ordering': ['nome'], 'permissions': (('editar_agente', 'Pode editar Agente'), ('deletar_agente', 'Pode deletar Agente')), 'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes'},
        ),
    ]
